apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: buyer.com
      http:
        paths:
          - path: /buyer
            pathType: Prefix
            backend:
              service:
                name: buyer-clusterip-srv
                port:
                  number: 4000